{% set name = "bermuda" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bermuda-{{ version }}.tar.gz
  sha256: 0aec1408603798fe4c9aa1cbfc4c3adbc5a539fadf73d850601f9f8a124e5bb3

build:
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 1
  ignore_run_exports:
    from_package:
      - cross-python_${{ target_platform }}  # [build_platform != target_platform]


requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - setuptools
    - setuptools-rust
    - setuptools-scm >=8.1
    - pip
  run:
    - python
    - numpy >=1.22.2

test:
  imports:
    - bermuda
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  summary: Spatial algorithms for napari project, compiled for performance
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  home: https://github.com/napari/bermuda

extra:
  recipe-maintainers:
    - czaki
    - jni
    - kevinyamauchi
    - kephale
    - DragaDoncila
